### ISSUE TITLE
pubsub not removing disconnected clients

### ISSUE THREAD

**Issue by sebstyle** [lesismal/arpc#20]
When subscribing client disconnects from server without unsubscribing first pupsub.Server.Publish() gives error:
`2021/09/22 19:04:49.612 [ERR] [Publish] [topic: 'Broadcast'] failed client stopped, from Server to     127.0.0.1:35306`

From reading the code regarding pupsub.NewServer()
`svr.Handler.HandleDisconnected(svr.deleteClient)`
Publish() should no longer be trying to send to a disconnected client but this does not seem to be working?

I do see the client disconnecting in log:
`2021/09/22 19:04:30.206 [ERR] [APS SVR] 127.0.0.1:35306 Disconnected: EOF`

I tried also to do this manually but when I add to code:
```
srv.Handler.HandleDisconnected(func (c *arpc.Client) {
    log.Error().Msg("HANDLE_DISCONNECTED_TEST")
})
```
Nothing happens either..

**Comment by lesismal** [comment]
If you get this log of the disconnected client from the server-side only at the same time of the disconnecting, that's because the server's publishing and the client's disconnecting happened in different goroutines nearly the same time:
1. When the server call Publish but has not pushed the msg to the client send queue, the client is still alive.
2. The client disconnected, the disconnected handler will clear the client's topics but can not stop the server's pushing msg operation.
3. The server pushed the msg, and get an error of the client has stopped.
4. If there are many different goroutines Publish at the same time of the disconnecting, each of the callings of Publish may get this error log.

`The disconnected handler will clear the client's topics` —— this may be finished before or after 3, because they are running in different goroutines.

It's not a problem if you don't get this log again when you Publish after the client has disconnected for some time for which we can make sure the disconnected handler has done about the clear job:
`2021/09/22 19:04:49.612 [ERR] [Publish] [topic: 'Broadcast'] failed client stopped, from Server to 127.0.0.1:35306`

If you are sure that something went wrong, please provide the full examples that can reproduce your problem, I'll check it.

**Comment by sebstyle** [comment]
I do not think this is the case.
1. I start pubsub.Server.Serve(listener) in a seperate go routine.
2. I start pubsub.Server.Publish() in a seperate go routine on a 15second interval
3. Client connects and subscribes
4. Client disconnects without unsubscribing
5. The Publish() interval goes after 15seconds and the error appears

**Comment by lesismal** [comment]
I can't reproduce your problem by this example:
https://github.com/lesismal/arpc/tree/master/examples/pubsub

It will help If you provide the full examples that can reproduce your problem.

**Comment by sebstyle** [comment]
Okay i did an `go get -u github.com/lesismal/arpc`
And now I am getting the expected info log when a client disconnects:
`2021/09/22 22:17:09.503 [INF] [APS SVR] [Disconnected Unsubscribe] [topic: 'jwtUpdates'] from   127.0.0.1:35838`
And the server no longer produces the aforementioned error.
So that seems to be working with latest update.

One more question if thats okay:
pubsub.NewClient() already does:
```
	cli.Handler.HandleConnected(func(c *arpc.Client) {
		if cli.Authenticate() == nil {
			cli.initTopics()
		}
	})
```
In the pubsub example Authenticate() is called again.. I assume this is only applies because if the password was set after NewClient() ?
And I often get these errors on the client:
```
2021/09/22 22:21:54.966 [INF] [ARPC CLI]	127.0.0.1:8181	Connected
2021/09/22 22:21:59.967 [ERR] [APS CLI] [Subscribe] [topic: 'jwtUpdates'] failed: timeout, from	127.0.0.1:8181
2021/09/22 22:21:59.968 [ERR] [APS CLI] [Authenticate] failed: timeout, from	127.0.0.1:8181
2021/09/22 22:21:59.968 [WRN] [APS CLI] OnMessage: session not exist or expired
```
While on server:
```
2021/09/22 22:21:54.966 [INF] [APS SVR] 127.0.0.1:35864 Connected
2021/09/22 22:21:54.966 [INF] [APS SVR] [Authenticate] success from     127.0.0.1:35864
2021/09/22 22:21:56.967 [INF] [APS SVR] [Subscribe] [topic: 'jwtUpdates'] success from  127.0.0.1:35864
```
I have no idea how to fix this unreliable Authenticate() / Subscribe()
Should be a strait forward thing one would expect.. any ideas?

**Comment by lesismal** [comment]
It will help If you provide the full examples that can reproduce your problem.

`the full examples` means the code including server and client.

**Comment by sebstyle** [comment]
I am no longer using the pubsub extension and switched to basic client/server with broadcast example.
This way I have more control over what happens.
Sorry for not being able to provide a means to reproduce the problems I encountered.

I was wondering how to implement the gRPC equivalent of server side stream?
Or any other suggestions/examples how to transfer large amounts of data on an rpc call.
I need to sync a large amount of token data between a master (server) and a slave (client)

Or is this as simple as concatenating all data into a super large string and ctx.Write() it?
Quite possibly using the gzip codec ?

**Comment by lesismal** [comment]
arpc is not GRPC, why should an rpc-framework support another rpc-framework? :joy: 
If you want GRPC, just use GRPC :joy:

 About data transfer: check the examples about Notify or Broadcast.

Here is a coder middleware example for gzip:
https://github.com/lesismal/arpc/tree/master/examples/middleware/coder/gzip

BTW, we'd better close this issue if you are not sure whether it is a problem of arpc, and create a new issue about other questions.

**Comment by sebstyle** [comment]
Yes sorry you are right this is probably not the place for it.
I'm kinda new to RPC stuff so I guess I was just looking for an opinion on how to do certain things the right way :)
Thanks for your replies!
